language: java

matrix:
  include:
  - os: linux
    dist: trusty
    env:
      - JDK: openjdk11
      - GDAL_VERSION: 2.2.*
      - GDAL_PPA: "ppa:ubuntugis/ppa"
  - os: linux
    dist: bionic
    env:
      - JDK: openjdk11
      - GDAL_VERSION: 2.4.*
      - GDAL_PPA: "ppa:ubuntugis/ubuntugis-unstable"

notifications:
  email: false

before_install:
  - if [ ! -z "${GDAL_PPA}" ]; then sudo add-apt-repository ${GDAL_PPA} -y; fi
  - sudo apt-get -qq update
  - sudo apt-get install -y gdal-bin=${GDAL_VERSION}

install: true

script:
  - ogr2ogr --version
  - ./travis/build-${JDK}.sh

cache:
  directories:
  - $HOME/.m2
