dist: trusty
language: java

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gdal-bin
  - ogr2ogr --version

jdk:
  - openjdk7

install: true

script:
- mvn clean package
