language: java

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gdal-bin

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

install: true

script: 
- mvn clean package -P cnig

