language: java

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y gdal-bin

jdk:
  - oraclejdk7
  - openjdk7

install: true

script:
- mvn clean package
