dist: trusty
language: java

notifications:
  email: false

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -qq update
  - sudo apt-get install -y gdal-bin=1.*
  - ogr2ogr --version

jdk:
  - openjdk7

install: true

script:
- mvn clean package
