name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install ogr2ogr
      run: |
        sudo apt-get -y install gdal-bin=3.6.4
        which ogr2ogr

    - name: Build and test
      run: bash .ci/build-openjdk11.sh

